version: 0.2

phases:
  pre_build:
    commands:
      # 기본 경로는 프로젝트 루트 폴더
      # npm install과 동일하지만 ci/cd에 더 좋음
      - cd library-frontend && npm ci
  build:
    commands:
      # Next.js 빌드
      - cd library-frontend && npm run build

      # SpringBoot 빌드
      - chmod +x ./library-backend/gradlew
      - ./library-backend/gradlew -p ./library-backend bootJar -x test
  post_build:
    commands:
      # deploy-frontend, deploy-backend 폴더 생성 (배포할 폴더)
      - mkdir -p deploy-frontend
      - mkdir -p deploy-backend

      # 프론트엔드 처리
      - cp -r library-frontend/.next deploy-frontend/
      - rm -rf deploy-frontend/.next/cache
      - cp library-frontend/package.json deploy-frontend/
      - cp library-frontend/package-lock.json deploy-frontend/
      - cp library-frontend/Procfile deploy-frontend/
      # next.config.ts가 있으면 복사, 없으면 그냥 넘어감
      - '[ -f library-frontend/next.config.ts ] && cp library-frontend/next.config.ts deploy-frontend/ || true'
      - '[ -d library-frontend/public ] && cp -r library-frontend/public deploy-frontend/ || true'

      #백엔드 처리
      - cp library-backend/build/libs/library-app.jar deploy-backend/
      - cp library-backend/Procfile deploy-backend/

# CodeBuild가 빌드 후 어떤 결과물을 CodePipeline으로 넘길지 지정
artifacts:
  secondary-artifacts:
    frontend-artifact:
      files:
        # 모든 파일 포함
        - '**/*'
      # 이 폴더를 기준으로 작업
      base-directory: deploy-frontend
    backend-artifact:
      files:
        - '**/*'
      base-directory: deploy-backend