spring:
  application:
    name: library-backend

  datasource:
    driver-class-name: org.h2.Driver
    hikari:
      username: sa
      password:
    url: jdbc:h2:mem:library
  jpa:
    hibernate:
      ddl-auto: create-drop
    defer-datasource-initialization: true